version: '3.1'

services:
  api:
    build: .
    container_name: backend_lumincoin_finance
    ports:
      - '3333:3333'
    volumes:
      - .:/app
      - ./data:/app/data
      - /app/node_modules

